FROM ultralytics/ultralytics:latest-cpu

WORKDIR /app

RUN pip install --no-cache-dir fastapi "uvicorn[standard]" python-multipart

COPY app.py .
COPY best.pt .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
